### PR TITLE
fix: correct artifact upload target directories for html and pdf documentation

### PR DESCRIPTION
**Pull request by moe-ad**
Expanding on the title, the directories being targeted by the action uploading the html and pdf documentation is incorrect. Corrected this (see the contents of tox.ini/Makefile).

### CODE REVIEW

**Review by jorgepiloto — APPROVED** [review]
Good catch, @moe-ad!

**Comment by moe-ad** [comment]
@jorgepiloto any idea why xvfb failed to start?

**Review by MaxJPRey — APPROVED** [review]
Nice catch @moe-ad

**Comment by RobPasMue** [comment]
Looks like the headless display action fixed it

**Pull request merged**
